package com.moretale.domain.story.service.impl;

import com.moretale.domain.story.dto.StoryGenerateRequest;
import com.moretale.domain.story.dto.StoryGenerateResponse;
import com.moretale.domain.story.dto.StoryGenerationJobResponse;
import com.moretale.domain.story.service.AIStoryService;
import com.moretale.global.config.MoreTaleProperties;
import com.moretale.global.exception.BusinessException;
import com.moretale.global.exception.ErrorCode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestClientResponseException;

import java.util.LinkedHashMap;
import java.util.Map;

@Service
@RequiredArgsConstructor
@Slf4j
public class AIStoryServiceImpl implements AIStoryService {

    private final MoreTaleProperties properties;
    private final RestClient.Builder restClientBuilder;

    @Override
    public StoryGenerationJobResponse enqueueStoryJob(
            StoryGenerateRequest request,
            String callbackUrl,
            String requestId
    ) {
        Map<String, Object> payload = new LinkedHashMap<>();
        putIfPresent(payload, "callbackUrl", callbackUrl);
        putIfPresent(payload, "requestId", requestId);
        putIfPresent(payload, "prompt", request.getPrompt());
        putIfPresent(payload, "profileId", request.getProfileId());
        putIfPresent(payload, "childName", request.getChildName());
        putIfPresent(payload, "primaryLanguage", request.getPrimaryLanguage());
        putIfPresent(payload, "secondaryLanguage", request.getSecondaryLanguage());
        putIfPresent(payload, "ageGroup", request.getAgeGroup());
        putIfPresent(payload, "childAge", request.getChildAge());
        putIfPresent(payload, "firstLanguageProficiency", request.getFirstLanguageProficiency());
        putIfPresent(payload, "secondLanguageProficiency", request.getSecondLanguageProficiency());
        putIfPresent(payload, "firstLanguageListening", request.getFirstLanguageListening());
        putIfPresent(payload, "firstLanguageSpeaking", request.getFirstLanguageSpeaking());
        putIfPresent(payload, "secondLanguageListening", request.getSecondLanguageListening());
        putIfPresent(payload, "secondLanguageSpeaking", request.getSecondLanguageSpeaking());
        putIfPresent(payload, "storyPreference", request.getStoryPreference());
        putIfPresent(payload, "customStoryPreference", request.getCustomStoryPreference());
        putIfPresent(payload, "autoGenerated", request.getAutoGenerated());
        putIfPresent(payload, "recommendedTaleTitle", request.getRecommendedTaleTitle());

        try {
            StoryGenerationJobResponse aiResponse = aiClient().post()
                    .uri("/internal/ai/story/jobs")
                    .body(payload)
                    .retrieve()
                    .body(StoryGenerationJobResponse.class);
            return toBackendJobResponse(aiResponse);
        } catch (RestClientException e) {
            log.error("AI story job 생성 요청 실패", e);
            throw new BusinessException(ErrorCode.AI_SERVICE_ERROR);
        }
    }

    @Override
    public StoryGenerationJobResponse getStoryJobStatus(String jobId) {
        try {
            StoryGenerationJobResponse aiResponse = aiClient().get()
                    .uri("/internal/ai/jobs/{jobId}", jobId)
                    .retrieve()
                    .body(StoryGenerationJobResponse.class);
            return toBackendJobResponse(aiResponse);
        } catch (RestClientResponseException e) {
            throw mapAiResponseException(e, "AI story job 상태 조회 실패 - jobId=" + jobId);
        } catch (RestClientException e) {
            log.error("AI story job 상태 조회 실패 - jobId={}", jobId, e);
            throw new BusinessException(ErrorCode.AI_SERVICE_ERROR);
        }
    }

    @Override
    public StoryGenerateResponse getStoryJobResult(String jobId) {
        try {
            AiStoryResultEnvelope result = aiClient().get()
                    .uri("/internal/ai/story/jobs/{jobId}/result", jobId)
                    .retrieve()
                    .body(AiStoryResultEnvelope.class);
            if (result == null || result.data == null) {
                throw new BusinessException(ErrorCode.AI_RESPONSE_INVALID);
            }
            return result.data;
        } catch (RestClientResponseException e) {
            throw mapAiResponseException(e, "AI story job 결과 조회 실패 - jobId=" + jobId);
        } catch (RestClientException e) {
            log.error("AI story job 결과 조회 실패 - jobId={}", jobId, e);
            throw new BusinessException(ErrorCode.AI_SERVICE_ERROR);
        }
    }

    private RestClient aiClient() {
        MoreTaleProperties.Ai ai = properties.getAi();
        RestClient.Builder builder = restClientBuilder.baseUrl(ai.resolveBaseUrl());
        if (ai.getApiKey() != null && !ai.getApiKey().isBlank()) {
            builder.defaultHeader("X-API-Key", ai.getApiKey());
        }
        return builder.build();
    }

    private void putIfPresent(Map<String, Object> payload, String key, Object value) {
        if (value != null) {
            payload.put(key, value);
        }
    }

    private StoryGenerationJobResponse toBackendJobResponse(StoryGenerationJobResponse aiResponse) {
        if (aiResponse == null || aiResponse.getJobId() == null) {
            throw new BusinessException(ErrorCode.AI_RESPONSE_INVALID);
        }
        String jobId = aiResponse.getJobId();
        return StoryGenerationJobResponse.builder()
                .jobId(jobId)
                .status(aiResponse.getStatus())
                .statusUrl("/api/stories/generation-jobs/" + jobId)
                .resultUrl("/api/stories/generation-jobs/" + jobId + "/result")
                .callbackUrl(aiResponse.getCallbackUrl())
                .build();
    }

    private BusinessException mapAiResponseException(
            RestClientResponseException e,
            String logMessage
    ) {
        log.error("{} - status={}", logMessage, e.getStatusCode(), e);
        if (e.getStatusCode().value() == 404) {
            return new BusinessException(ErrorCode.STORY_GENERATION_JOB_NOT_FOUND);
        }
        if (e.getStatusCode().value() == 409) {
            return new BusinessException(ErrorCode.STORY_GENERATION_NOT_READY);
        }
        return new BusinessException(ErrorCode.AI_SERVICE_ERROR);
    }

    private static class AiStoryResultEnvelope {
        public String jobId;
        public String type;
        public String status;
        public StoryGenerateResponse data;
        public Map<String, Object> error;
    }
}
