package com.moretale.domain.story.dto;

import com.moretale.domain.profile.entity.AgeGroup;
import com.moretale.domain.profile.entity.LanguageProficiency;
import com.moretale.domain.profile.entity.StoryPreference;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "동화 생성 요청 DTO")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StoryGenerateRequest {

    @NotBlank(message = "프롬프트를 입력해주세요.")
    @Schema(description = "동화 생성 프롬프트 (주제 또는 내용)", example = "토끼와 거북이가 우주로 여행을 떠나는 이야기")
    private String prompt;

    @Schema(description = "프로필 ID (미입력 시 가장 최근 프로필 사용)", example = "1")
    private Long profileId;

    @Schema(description = "주인공 아이 이름 (미입력 시 프로필 값 사용)", example = "민준")
    private String childName;

    @Schema(description = "제1언어 ISO 코드 (예: ko, en, vi). 미입력 시 프로필 값 사용", example = "ko")
    private String primaryLanguage;

    @Schema(description = "제2언어 ISO 코드 (예: vi, en, ja). 미입력 시 프로필 값 사용", example = "vi")
    private String secondaryLanguage;

    @Schema(description = "나이 그룹 (미입력 시 프로필 값 사용)", example = "AGE_5_6")
    private AgeGroup ageGroup;

    @Schema(description = "실제 나이 (ageGroup에서 자동 계산)", example = "5")
    private Integer childAge;

    @Schema(description = "제1언어 전체 숙련도", example = "BEE")
    private LanguageProficiency firstLanguageProficiency;

    @Schema(description = "제2언어 전체 숙련도", example = "LARVA")
    private LanguageProficiency secondLanguageProficiency;

    @Schema(description = "제1언어 듣기 능력", example = "BEE")
    private LanguageProficiency firstLanguageListening;

    @Schema(description = "제1언어 말하기 능력", example = "PUPA")
    private LanguageProficiency firstLanguageSpeaking;

    @Schema(description = "제2언어 듣기 능력", example = "LARVA")
    private LanguageProficiency secondLanguageListening;

    @Schema(description = "제2언어 말하기 능력", example = "EGG")
    private LanguageProficiency secondLanguageSpeaking;

    @Schema(description = "이야기 선호도", example = "FUN_ADVENTURE")
    private StoryPreference storyPreference;

    @Schema(description = "이야기 선호도 직접 입력 (CUSTOM 시)", example = "우주 탐험 이야기")
    private String customStoryPreference;

    @Schema(description = "온보딩 직후 자동 생성 여부", example = "false")
    @Builder.Default
    private Boolean autoGenerated = false;

    @Schema(description = "추천 전래동화 제목 (자동 매핑된 경우)", example = "흥부와 놀부")
    private String recommendedTaleTitle;
}
